### ISSUE TITLE
Multiline tooltips

### ISSUE THREAD

**Issue by LaineZ** [coding-jackalope/Slab#15]
If i tried make multiline tooltip witn ```\n``` character it is not displayed correctly
![Bug](https://i.imgur.com/aBA0gVv.png)
Code:
``slab.Button("GC", {Tooltip = "Performs a garbage collection:\nLua uses a garbage collector that runs from time to time to collect dead objects when they are no longer accessible from the Lua program."})``

**Comment by coding-jackalope** [comment]
This issue should now be fixed with the latest release. The commit can be found here 87231b88c7dca1ee2173c28b37d1d7d864e08646.
