### ISSUE TITLE
Window Close Behaviour 

### ISSUE THREAD

**Issue by flamendless** [coding-jackalope/Slab#16]
Really awesome for the close button feature! Thanks!

I strongly recommend to add an example of how to properly use the `IsOpen` (close button) for the Window API in the wiki.

First I've tried this
```lua
local test = true
--in update
if test then
  Slab.BeginWindow("Test", {Title = "Test", IsOpen = test})
  Slab.EndWindow()
end
```
which shows properly the close open, but clicking it still shows the window, and printing the value of `test` results to always being true. Now the reason for this is simple, because if we pass a value like boolean in a function, the value is passed as a copy instead of a reference.

Second, I've tried passing a table so as an alternative to Lua pass by reference
```lua
local test = {Title = "Test", IsOpen = true}
--in update
if test then
  Slab.BeginWindow("Test", test)
  Slab.EndWindow()
end
```
This works, but somehow counter intuitive for me having to define the `options` table outside.

Perhaps, just like in the love-bindings for DearImGui, the `BeginWindow` returns a boolean value.

The usage would be
```lua
local test = true
--in update
if test then
  test = Slab.BeginWindow("Test, {Title = "Test", IsOpen = test})
  Slab.EndWindow()
end
```

**Comment by flamendless** [comment]
This is a reference to the love-imgui binding I mentioned
https://github.com/slages/love-imgui
```lua
    if showAnotherWindow then
        imgui.SetNextWindowPos(50, 50, "ImGuiCond_FirstUseEver")
        showAnotherWindow = imgui.Begin("Another Window", true, { "ImGuiWindowFlags_AlwaysAutoResize", "ImGuiWindowFlags_NoTitleBar" });
        imgui.Text("Hello");
        -- Input text
        textValue = imgui.InputTextMultiline("InputText", textValue, 200, 300, 200);
        imgui.End();
    end
```

**Comment by coding-jackalope** [comment]
Thanks for the feedback! I have updated the wiki to provide some example code on usage for IsOpen.

I will also look at implementing the return value for the open state of the window. It seems like love-imgui makes use of this among other uses of return values. Thanks for linking the example.
