### ISSUE TITLE
ListBox Items Selectable Through GUI

### ISSUE THREAD

**Issue by SweetAlmighty** [coding-jackalope/Slab#19]
First off, I wanted to say thanks for the library! It's been great to work with, and was exactly what I was looking for to start on my Animation tool project.

The attached gif shows an issue I noticed, where a list box item that was offscreen would be selected if I attempted to select a different UI element that was being drawn over that list box item

![listbox](https://user-images.githubusercontent.com/2686731/81355032-29923600-909b-11ea-848e-7901c5045492.gif)

I noticed that there is "Slab.IsControlHovered()", and I was able to use that to determine if the list box item should be selected. I was wondering if that was the expected way to get around this issue, or if there were any plans to fix this inside the library.

Thanks in advanced for your reply!

**Comment by coding-jackalope** [comment]
Hi, thanks for the report. Using "Slab.IsControlHovered()" should be a good temporary fix for now, but I will have a proper fix in for the next update. Will update this thread once the fix is in.

**Comment by coding-jackalope** [comment]
This issue has been fixed in release v0.6.4. The commit can be found here f673a39.
