### ISSUE TITLE
The screen blinks when I press the right mouse button

### ISSUE THREAD

**Issue by BestHatzker** [coding-jackalope/Slab#2]
The screen blinks when I press the right mouse button. Under the blink, I mean the brightness plays a little

**Comment by BestHatzker** [comment]
Blinks when i press processed keys in love.keypressed(key)

**Comment by BestHatzker** [comment]
We have both buttons screwed to redraw the screen... probably this is the case

**Comment by BestHatzker** [comment]
Further research has shown that the window with Love is lighter without using Slab. and therefore when redrawing and blinking

**Comment by coding-jackalope** [comment]
Hi BestHatzker,

When you say screen, do you mean the viewport presented by Love, or do you mean a Slab window? Also, could you provide a gif showing this behavior? This would be helpful in figuring out what the issue may be. Thanks.

**Comment by BestHatzker** [comment]
It was a problem with the incorrect placement of slab.update in our program. we are doing well now. thank
