### ISSUE TITLE
Scrolling permanently breaks any intereaction

### ISSUE THREAD

**Issue by krassell** [coding-jackalope/Slab#3]
Slab stops reacting to any kind of mouse interaction and [almost any] keyboard interaction if you scroll your mousewheel in certain areas.

Scrolling while hovering over combo boxes, input fields and window titles triggers this reliably for me.

**Comment by coding-jackalope** [comment]
Hi krassell,

Sorry for the late reply. I was able to reproduce this issue and will looking at a fix for this in the next update. Thanks.

**Comment by coding-jackalope** [comment]
Hi krasell,

I went ahead and added the fix to this issue on the main branch and put out release version 0.6.1 that contains this fix. Try this release out when you get a chance and let me know if this issue still persists. If not, I will close this issue within a week.

**Comment by krassell** [comment]
It indeed has stopped happening, although there is a minor bug where the WheelY doesn't get consumed when you scroll with mouse pointer over aforementioned elements and it then gets applied as soon as you move cursor out of that object. 
So if you tried to scroll in input field/combo box and moved mouse out, it'd scroll parent window by your last mousewheel delta.

**Comment by coding-jackalope** [comment]
Ah yes, I do notice this too. This one is minor compared to the previous issue so I will have a fix for this in the next update. Thanks for the info.
