### ISSUE TITLE
Bug: Slab fails to load styles when it's not in the top level of a love2d project

### ISSUE THREAD

**Issue by idbrii** [coding-jackalope/Slab#30]
I modify my path in conf.lua to allow me to split my code into two
folders: src/ and src/lib/
```lua
love.filesystem.setRequirePath("src/?.lua;src/?/init.lua;src/lib/?.lua;src/lib/?/init.lua")
```
This allows me to import modules from either folder without any
prefixes:
```lua
local Slab = require 'Slab'
```
This doesn't work with Slab. Even excluding lib from require path (so it
must be specified in includes) doesn't work with Slab.

# Investigation

Slab sets its path using the require path:
```lua
SLAB_PATH = ...
```
But styles use this as if it were a filesystem path (that ignores lua's
require path):

```lua
  local StylePath = "/Internal/Resources/Styles/"
  local Path = SLAB_PATH .. StylePath
  Path = string.gsub(Path, "%.", "/")
  -- Use love's filesystem functions to support both packaged and unpackaged builds
  local Items = love.filesystem.getDirectoryItems(Path)
```

Styles fail to load and every execution outputs this error:
```
  Style 'Dark' is not loaded.
```
So far, nothing looks wrong, but it does mean I can't use styles.

Two solutions I can see is for styles to search for the style folder using
love.filesystem.getRequirePath or be lua files that can use `require()`. My preference is the latter (removes style parser implementation, familiar data format), but I'd assume it's more work (style editor).
 

Repro example in my  [repro-style-load-path branch](https://github.com/idbrii/love-slab/tree/repro-style-load-path). I moved Slab's files around to replicate a real project. See how I moved things around in idbrii/love-slab@cc89b7e575eecf3d0d004029298f0e00aee01cdd.

**Comment by sdleffler** [comment]
A similar issue happens when using `Slab.FileDialog`. Slab crashes because it can't open the image file. The cause seems to be here, lines 116-122 of `Dialog.lua` in my local repository:

```lua
local function FileDialogItem(Id, Label, IsDirectory, Index)
	ListBox.BeginItem(Id, {Selected = Utility.HasValue(ActiveInstance.Selected, Index)})

	if IsDirectory then
		Image.Begin('FileDialog_Folder', {Path = SLAB_PATH .. "/Internal/Resources/Textures/Folder.png"})
		Cursor.SameLine({CenterY = true})
	end
```

Changing `SLAB_PATH` to `SLAB_PATH:gsub("%.", "/")` fixes the issue. I think it may be a good idea to add a `SLAB_FILEPATH = SLAP_PATH:gsub("%.", "/")` global to the `init.lua` or wherever else `SLAB_PATH` is set, and possibly rename `SLAB_PATH` to `SLAB_MODULE_PATH` to avoid confusion.

**Comment by sdleffler** [comment]
Ah, there's already a PR to deal with this, somewhat: #21

**Comment by idbrii** [comment]
I can confirm this works for me on an example project with my setRequirePath line above and slab in ./src/lib/slab.

Unfortunately, it doesn't work in my current project, but I guess something else is interfering. I'll have to investigate more later. Thanks for fixing!
