### ISSUE TITLE
Windows do not notice when mouse is released after they are closed

### ISSUE THREAD

**Issue by sdleffler** [coding-jackalope/Slab#31]
Hi! I have two windows, call them window A and window B. Window A contains a button which opens up window B. Window B is closable, so it has that nice lil `X` in the top right that you can click to make it buzz off. So, what's happening here is that I open window B from window A's button; then, I close window B. At this point, it appears that window B still thinks it is being dragged around; when I re-open window B using my button on window A, then whenever the cursor isn't hovering over window A, window B thinks it's getting dragged around. This causes some odd behavior. I think all that's needed to fix this is to set `Instance.IsMoving = False` on close; I'll test that shortly.

**Comment by sdleffler** [comment]
To clarify: clicking that wonderful little `X` causes window B to have its `IsMoving` flag set, as well as close it, at the same time. Because it is closed when the mouse is released, it doesn't have `IsMoving` unset until it is opened again and the mouse is pressed and released. And, after some testing it seems like adding `ActiveInstance.IsMoving = false` to the `if` clause which sets `ActiveInstance.IsOpen = False` on the window being closed does fix the issue. I'm not sure if this is the sort of solution that would be preferred here or if there's some other way that closed windows get notified of events though.

**Comment by coding-jackalope** [comment]
Thanks for reporting this issue. I integrated your fix and attributed you as the author for this fix. The commit can be found at 7836682. This will be deployed with the next update.
