### ISSUE TITLE
[WIKI] Use Slab.GetInputNumber for numbers

### ISSUE THREAD

**Issue by flamendless** [coding-jackalope/Slab#36]
Hi, i've noticed that in the wiki, under the "getting numbers", it uses `tonumber(Slab.GetInputText())`:
```lua
if Slab.Input('MyInput', {Text = tostring(Value), ReturnOnText = false, NumbersOnly = true}) then
	Value = tonumber(Slab.GetInputText())
end
```
I suggest to use the API `Slab.GetInputText()` to save call so as not to use `tonumber` anymore since it is explicitly stated to get numbers only with the config `NumbersOnly = true`

**Comment by coding-jackalope** [comment]
Thanks for reporting this. I have made the necessary change in the wiki.
