### ISSUE TITLE
Input's drag functionality is too sensitive for small ranges

### ISSUE THREAD

**Issue by idbrii** [coding-jackalope/Slab#38]
If I want an integer value in [0,10], then there are only 11 possible values. Instead of using the full width (or half width) of the slider to adjust through this range, InputNumberDrag accepts tiny movements to adjust. It only takes the width of one character to move through the entire input range.

Using InputNumberSlider is much better. Could InputNumberDrag work the same way (or maybe scaled to require less movement)?

Example (or run SlabTest and set these values):

```lua
local DrawInput_Basic_Numbers_Clamped_Options =
{
    Text = tostring(DrawInput_Basic_Numbers_Clamped),
    NumbersOnly = true,
    MinNumber = 0,
    MaxNumber = 10,
    Step = 1,
}
if Slab.Input('DrawInput_Basic_Numbers_Clamped', DrawInput_Basic_Numbers_Clamped_Options) then
    DrawInput_Basic_Numbers_Clamped = Slab.GetInputNumber()
end
```

**Comment by coding-jackalope** [comment]
Thanks for the feedback @idbrii. I'll look into implementing this for the next patch release.
