### ISSUE TITLE
How can I overlay one image on another with a transparent background using Slab.Image?

### ISSUE THREAD

**Issue by BestHatzker** [coding-jackalope/Slab#4]
I studied Wiki (Image, Layouts and Window), but dont understand how i can do this. Please explain to me

**Comment by coding-jackalope** [comment]
Hi BestHatzker,

Correct me if I am misunderstanding this, but from your question it seems you want to draw two different images on top of each other. To do this, you just need to place the cursor back at the position of the first image drawn.

```lua
local X, Y = Slab.GetCursorPos()
Slab.Image('Image_Bottom', {Path = "image1.png"})
Slab.SetCursorPos(X, Y)
Slab.Image('Image_Top', {Path = "image2.png"})
```

If this isn't what you are looking for, please elaborate what it is you are trying to accomplish and possibly provide a screenshot.

**Comment by BestHatzker** [comment]
Thank you! It's really work :)
