### ISSUE TITLE
Image - allow passing of quad and image and more

### ISSUE THREAD

**Issue by flamendless** [coding-jackalope/Slab#52]
Hi, it would be useful to allow something like:
```lua
Slab.Image("Animation", {
  Title = "Animation",
  Image = spritesheet,
  Quad = quad
})
```
As an alternative to `Sub(x,y,w,h)`

---

Also, for clarification, does the `Sub` variant in `Image` does the same as quad or it's for controlling how the image is drawn in the widget?

I've noticed that using the `Scale` with `Sub` variants makes the image overflow in the widget without the widget size and succeeding elements adjust properly.

**Comment by coding-jackalope** [comment]
Hi @flamendless, thanks for the suggestion. I'll add this to the upcoming patch release.

The Sub variant will actually create a quad with the given settings and will reference the texture coordinates supplied in the call. Slab should then add the widget based on the bounds of the quad. If not, I'll try to reproduce the issue and fix it for the upcoming release.

**Comment by flamendless** [comment]
Oh i mistyped the last part. I meant that using the `Scale` with the `Sub` variants makes the image overflow the window. It also overlaps behind other widgets.
