### ISSUE TITLE
ContextMenuItem breaks layouts using SameLine

### ISSUE THREAD

**Issue by antoniotorresm** [coding-jackalope/Slab#56]
When using buttons in a horizontal layout (using Slab.SameLine), calling a ContextMenuItem on one of them breaks the layout.
Reproduction project: [slab-bug.zip](https://github.com/coding-jackalope/Slab/files/5334038/slab-bug.zip)

![image](https://user-images.githubusercontent.com/17461846/95206647-3c926900-07e7-11eb-9c0b-097c23163a58.png)
![image](https://user-images.githubusercontent.com/17461846/95206688-461bd100-07e7-11eb-962e-44b2eba8b18b.png)

**Comment by coding-jackalope** [comment]
Hi @antoniotorresm, thanks for reporting this. Should be an easy fix that will be included in the next upcoming patch release.
