### ISSUE TITLE
example crash

### ISSUE THREAD

**Issue by boris-741** [coding-jackalope/Slab#58]
Error: /Internal/Core/DrawCommands.lua:526: Cannot set scissor with negative width.
stack traceback:
        [string "boot.lua"]:777: in function <[string "boot.lua"]:773>
        [C]: in function 'assert'
        /Internal/Core/DrawCommands.lua:526: in function 'Scissor'
        /Internal/UI/Region.lua:468: in function 'ApplyScissor'
        /Internal/UI/Region.lua:345: in function 'Begin'
        /Internal/UI/Window.lua:639: in function 'BeginWindow'
        SlabTest.lua:1872: in function <SlabTest.lua:1678>
        SlabTest.lua:2375: in function 'Begin'
        main.lua:37: in function 'update'
        [string "boot.lua"]:612: in function <[string "boot.lua"]:594>
        [C]: in function 'xpcall'

**Comment by coding-jackalope** [comment]
Hi @boris-741, could you provide some example code or reproduction steps that is causing this issue? It would help in finding the culprit of this error.

**Comment by boris-741** [comment]
![image](https://user-images.githubusercontent.com/8223870/97906248-642c1100-1d54-11eb-931f-db5ddf733a08.png)
![image](https://user-images.githubusercontent.com/8223870/97906340-8756c080-1d54-11eb-8df2-6e4904872f2b.png)
1. start window example
2 drag the window off the love window bound

**Comment by coding-jackalope** [comment]
Thanks for the response. However, I was unable to reproduce this issue on versions 0.7.0 and the latest release 0.7.1. What version are you currently running and what OS is this error occurring on? Does this crash still occur for you with the latest version?

**Comment by boris-741** [comment]
slab - 0.7.1
love2d - 11.3
os: windows 10

**Comment by Veslo5** [comment]
@coding-jackalope 
Sorry again for bothering. I can reproduce it too. Hope this gif helps.

slab - 0.7.1
love2d - 11.3
os: windows 10

![bug](https://user-images.githubusercontent.com/24257206/98304179-c2106100-1fbf-11eb-8433-579c521310e8.gif)
