### ISSUE TITLE
Request for Sliders Input

### ISSUE THREAD

**Issue by flamendless** [coding-jackalope/Slab#6]
Hi, first of all, amazing library! It really is like coding using DearImGUI! Awesome. Keep up the good work :)

Aside from the clear title, is there any work/progress for sliders?

**Comment by coding-jackalope** [comment]
Hi flamendless, glad this library is helping you. Sliders is something I definitely want to support. I don't have an ETA unfortunately and development has been slow but will be picking back up in the coming ups. When I do have an update, I'll be sure to update you.

**Comment by flamendless** [comment]
Btw, i was thinking of implementing some kind of messaging logs or assertion (if user set it to enable) for passing properties wrong. I've spent a lot of time wondering why x isn't working, then found out it's due to "alignX" instead of "AlignX". What do you think?

**Comment by belohlavek** [comment]
I'll be doing some of this for my own app, no ETA either but will share a snippet with my work when it's done. Quality may not be good enough for a PR :)

**Comment by coding-jackalope** [comment]
> Btw, i was thinking of implementing some kind of messaging logs or assertion (if user set it to enable) for passing properties wrong. I've spent a lot of time wondering why x isn't working, then found out it's due to "alignX" instead of "AlignX". What do you think?

This is something I would like to have as well. While the documentation tries to have all the proper names listed for each property, there may be cases where it could be missing some. Also, having the quick feedback when running the application would help diagnose and solve problems sooner. I'll be sure to add this as a feature item in the coming updates.

**Comment by flamendless** [comment]
Alright then. I was about to make a PR for that, but you already got it handled then

**Comment by coding-jackalope** [comment]
@flamendless if you have a PR, I wouldn't mind taking a look at it and integrating it into the next release.
