### ISSUE TITLE
Window undock bad alignment on mouse coords 

### ISSUE THREAD

**Issue by Veslo5** [coding-jackalope/Slab#60]
Slab version 0.7.1
LOVE version 11.3.0
OS: Windows 10

Its happend only sometimes. Reproducted this issue on fullscreen too as well as from left and right dock.

Including gif:
![bug](https://user-images.githubusercontent.com/24257206/98218437-0b26cd80-1f4c-11eb-82f9-dbbee311cd3d.gif)

**Comment by coding-jackalope** [comment]
Thanks for reporting this @Veslo5. There will be a fix for this in the upcoming patch release.
