### ISSUE TITLE
Feature request: "Up to" button in file dialogs

### ISSUE THREAD

**Issue by LaineZ** [coding-jackalope/Slab#61]
It would be cool if File Dialogs will have this button - sometimes happens when you accidentally pick wrong folder and want to go back. But it cannot done in proper way. You need reopen file dialog again and complete full folder path again

![Save dialog in windows](https://i.imgur.com/ot8LPJY.png)

**Comment by coding-jackalope** [comment]
Hi @LaineZ, thanks for the suggestion. I'll look into implementing this for the next minor release.
