### ISSUE TITLE
`BeginMenu` and `ContextMenuWindow` missing top rounded corners

### ISSUE THREAD

**Issue by Dude112113** [coding-jackalope/Slab#63]
Just a note; I am still figuring out Slab, if I am missing something, my bad...

![image](https://user-images.githubusercontent.com/25151112/101070706-a0d96b00-3593-11eb-9b0d-9e37b08c02da.png)
![image](https://user-images.githubusercontent.com/25151112/101071243-3bd24500-3594-11eb-8057-49a8b52babc9.png)

The tops of the context menu's are missing rounded corners.
For the `MainMenuBar` it makes sense to not have rounded corners.

It does make sense to have no rounded corners in this case though
![image](https://user-images.githubusercontent.com/25151112/101071515-9ff50900-3594-11eb-807f-990ba1a82283.png)

Code (First Image)
```lua
if Slab.BeginContextMenuWindow() then
	Slab.MenuItem("BLANK")

	if Slab.BeginMenu("Create") then
		if Slab.MenuItem("Lamp") then
			print("Create Lamp")
		end

		if Slab.MenuItem("Button") then
			print("Create Lamp")
		end

		Slab.EndMenu()
	end

	Slab.EndContextMenu()
end
```

**Comment by coding-jackalope** [comment]
Hi @Dude112113, thanks for reporting this issue. The fix should be fairly trivial and will be included in the next update.
