### ISSUE TITLE
Scroll Speed

### ISSUE THREAD

**Issue by belohlavek** [coding-jackalope/Slab#7]
What was the rationale behind the choice of Region scroll speed?
It feels slow, I modified it for my usecase but saw someone who foked and did the same on their side.

**Comment by coding-jackalope** [comment]
This was just something I added to get the feature in. It should be dynamic and allow the user to set the scroll speed. I'll add a feature request for this.

**Comment by coding-jackalope** [comment]
This has been implemented in commit 390e009f9b16d62f6ddd46812547ed644166709a.
