### ISSUE TITLE
Error when Slab.Draw is called before Slab.Update

### ISSUE THREAD

**Issue by PhoenixAran** [coding-jackalope/Slab#74]
Slab Version: 0.7.2 

I get the following error:
**'Error: lib/slab/Internal/Core/DrawCommands.lua:356: attempt to index local 'Layer' (a nil value)'** 
when I override the love.run function as seen [here](https://gist.github.com/jakebesworth/ac09d54cc05690250096f977105a41f8
)

Here is a [minimal reproduction main.lua file](https://gist.github.com/PhoenixAran/8272ad1f65e6ea307252db3c174c1e4d) 
I believe this is caused by Slab.Draw() being called before the first Slab.Update() call.

In my current project I work around this by calling Slab.Update(0) after initializing Slab in love.load.
I also remove the check for DidDraw inside Slab.Draw since I notice some flickering if Slab.Draw() is called in an update loop where Slab.Update() got skipped.

**Comment by coding-jackalope** [comment]
Hi @PhoenixAran, thanks for reporting this issue. A fix for this will be included in the next release.
