### ISSUE TITLE
Wiki update for WINDOW

### ISSUE THREAD

**Issue by togfoxy** [coding-jackalope/Slab#75]
Small edits over time can result in a great product.  :)

This page:
https://github.com/coding-jackalope/Slab/wiki/Window
says:
Windows, by default, will have sizers for all sides active.

For clarity, windows, by default, use AutoSizeWindow and therefore do NOT have sizers by default. 

Suggested text:
Windows using auto-sizing (AutoSizeWindow = false) will have window edge sizers on all sides.

**Comment by coding-jackalope** [comment]
Hi @togfoxy, thanks for pointing this out. All fixes are always appreciated. This text is changed in a separate branch and will be updated when the new version is released.

**Comment by togfoxy** [comment]
Resolved as suggested.
